language: c
compiler:
  - gcc
  - clang
env:
  - MRUBY_VERSION=1.2.0
  - MRUBY_VERSION=1.3.0
  - MRUBY_VERSION=1.4.0
  - MRUBY_VERSION=master
before_install:
  - sudo apt-get -qq update
install:
  - sudo apt-get -qq install rake bison git gperf
script:
  - rake test
